### ISSUE TITLE
minBlockLength

### ISSUE THREAD

**Issue by zonkmachine** [portalmod/mod-pitchshifter#13]
`These effects are supposed to work well with the following values of Frames/Period: 64, 128, 256, 512`

The mod-pitchshifter plugins seem to work bad on a buffer size of 32 (Tested on lmms, [lv2 development branch](https://github.com/LMMS/lmms/pull/6484)). With a buffer size of 32 most of the plugins would crash and some would just not have an effect. Maybe it would be a good idea to add as requiredFeature a minBlockLength of 64 ?

Crash:
---
2Voices
Capo
Drop
SuperCapo
SuperWhammy

No effect:
---
Harmonizer
Harmonizer2

Not tested
---
HarmonizerCS

**Comment by falkTX** [comment]
That is not what that lv2 feature is for.
minBlockLength just asks the host to provide such value, which indicates the minimum block size used for audio.

the plugin could refuse to load on such hosts, but on MOD that never happens so there hasn't been the need for it.

**Comment by zonkmachine** [comment]
Thanks for the fast response!

I see, I have some reading up to do. We're blocking them on our side but in my mind at least it sounded like it belonged up-stream. Closing, rock on! 8)
